# NumPy

## Introduction

[NumPy Reference](https://numpy.org/doc/stable/reference)

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

## The Basics of NumPy Arrays 



### NumPy for Matlab users

MATLAB® and NumPy have a lot in common. But there are many differences. NumPy was created to do numerical and scientific computing in the most natural way with Python, not to be MATLAB® clones.

However, it might be useful to draw a parallel line between these two, if you are already familiar with MATLAB® matrix structures and methods. So, we advise you to consult the key differences and similataries between MATLAB® and NumPy [here](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html).

### The ndarray data structure

The core functionality of NumPy is its `ndarray`, for *n*-dimensional array, data structure. These arrays are strided views on memory. In contrast to Python's built-in list data structure, these arrays are homogeneously typed: all elements of a single array must be of the same type.

In [6]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(a.shape)           
print(a)  
a[0] = 5                  # Change an element of the array
print(a)

(3,)
[1 2 3]
[5 2 3]


## Array indexing

### Array slicing

Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array.

In [3]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
77


## Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [4]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

### Sum

In [6]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


### Difference

In [8]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


### Product

In [9]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


### Division

In [12]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


### Squareroot

In [13]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


### Inner product

## Reshaping arrays

## Array concatenation and spliting

In [2]:
import numpy as np

In [3]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [4]:
a + 5

array([5, 6, 7])

### Datatypes

Every NumPy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. NumPy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype.

Since NumPy is mostly written in C, these types map to C numeric types. You can check them all [here](https://numpy.org/devdocs/user/basics.types.html).

In [10]:
import numpy as np

x = np.array([1, 2])                   # Let numpy choose the datatype
print(x.dtype)         

x = np.array([1.0, 2.0])               # Let numpy choose the datatype
print(x.dtype)             

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                        

int32
float64
int64


## Broadcasting

Broadcasting allows these types of binary operations to be performed on arrays of different sizes–for example, we can just as easily add a scalar (think of it as a zero-dimensional array) to an array: