# Solutions

## Numpy 

In [1]:
import numpy as np

### Exercises

1. Create a vector of length 10 with values evenly distributed between 5 and 50.








In [2]:
np.linspace(5, 50, 10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

2. Create an array of shape (3, 2) filled with the number 5.

In [3]:
np.ones((3, 2)) * 5

array([[5., 5.],
       [5., 5.],
       [5., 5.]])

3. Convert the values of Fahrenheit degrees stored in `[0, 12, 45, 34, 99]` into Centigrade degrees.

In [4]:
(np.array([0, 12, 45, 34, 99]) - 32) / 1.8

array([-17.77777778, -11.11111111,   7.22222222,   1.11111111,
        37.22222222])

4. Get the indices of the elements that are bigger than 10 in `[[0, 10, 20], [20, 30, 40]]`.

In [5]:
np.argwhere(np.array([[0, 10, 20], [20, 30, 40]]) > 10)

array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]], dtype=int32)

5. Change the shape of `[1, 2, 3, 4, 5, 6]` to (3, 2) and select its first two rows.

In [6]:
np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2)[:2]

array([[1, 2],
       [3, 4]])

6. Calculate the inner product of [4, 5] and [7, 10].

In [7]:
np.dot(np.array([4, 5]), np.array([7, 10]))

78

7. Calculate the normalized vector perpendicular to `[1, 5, 3]` and `[8, 4, 2]`.

In [8]:
a = np.cross(np.array([1, 5, 3]), (np.array([8, 4, 2])))
a = a / np.linalg.norm(a)
a

array([-0.04735137,  0.5208651 , -0.8523247 ])

8. Subtract `[1, 0, 3]` from each row of the array `[[0, 0, 0], [1, 2, 3], [4, 5, 6]]` using broadcasting.

In [9]:
np.array([[0, 0, 0], [1, 2, 3], [4, 5, 6]]) - np.array([1, 0, 3])

array([[-1,  0, -3],
       [ 0,  2,  0],
       [ 3,  5,  3]])

## SymPy

In [51]:
from sympy import *

x, y = symbols("x y")
f, g = symbols('f g', cls=Function)

### Exercises

1. Find 100 digits of $\pi^{e}$

In [27]:
(pi ** E).n(100)

22.45915771836104547342715220454373502758931513399669224920300255406692604039911791231851975272714303

2. Expand $(x + y)^{2}(x - y)(x^{2} + y)$

In [18]:
((x + y) ** 2 * (x - y) + (x ** 2 + y)).expand()

x**3 + x**2*y + x**2 - x*y**2 - y**3 + y

3. Simplify $\frac{1}{x} + \frac{x sin(x) - 1}{x^{2} - 1}$

In [19]:
simplify((1 / x) + (x * sin(x) - 1) / (x ** 2 - 1))

(x**2*sin(x) + x**2 - x - 1)/(x**3 - x)

4. Find roots of $x^{4} - 4x^{3} + 2x^{2} - x$

In [28]:
solve(x ** 4 - 4 * x ** 3 + 2 * x ** 2 - x)

[0,
 4/3 + (-1/2 - sqrt(3)*I/2)*(sqrt(321)/18 + 83/54)**(1/3) + 10/(9*(-1/2 - sqrt(3)*I/2)*(sqrt(321)/18 + 83/54)**(1/3)),
 4/3 + 10/(9*(-1/2 + sqrt(3)*I/2)*(sqrt(321)/18 + 83/54)**(1/3)) + (-1/2 + sqrt(3)*I/2)*(sqrt(321)/18 + 83/54)**(1/3),
 10/(9*(sqrt(321)/18 + 83/54)**(1/3)) + 4/3 + (sqrt(321)/18 + 83/54)**(1/3)]

5. Solve the following equation system $x + y = 4$ and $x \cdot y = 3$

In [30]:
solve([x + y - 4, x * y - 3], [x, y])

[(1, 3), (3, 1)]

6. Calculate the left-sided limit of the function $\frac{|x|}{x}$

In [32]:
limit(abs(x) / x, x, 0, dir='-')

-1

7. Calculate the definite integral of the function $cos^{3}{x}$ between 0 and $\frac{\pi}{2}$

In [47]:
integrate(cos(x) ** 3, (x, 0, pi / 2))

2/3

8. Solve the differential equation $f''(x) + 9f(x) = 1$

In [53]:
dsolve(f(x).diff(x, x) + 9 * f(x) - 1, f(x))

Eq(f(x), C1*sin(3*x) + C2*cos(3*x) + 1/9)